name: Continuous Integration (ubuntu)

on:
  push:
    branches: [ master,CodeGeneration ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore BeethovenCi.sln
    - name: Build
      run: dotnet build BeethovenCi.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test BeethovenCi.sln --no-restore --verbosity normal
